branches:
  only:
    - master
language: c
compiler: gcc
install:
 - sudo apt-get update -qq
 - sudo apt-get install -y doxygen graphviz valgrind
 - wget http://ftp.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
 - tar xf lcov_1.11.orig.tar.gz
 - sudo make -C lcov-1.11/ install
 - rm -rf lcov-1.11
 - lcov --version
script: make test
after_success: ./build_pages.sh
env:
  global:
    - secure: "JS/6lbqPUbBRAUmwxDs7f67CEO1zB+BmuL9YUk/lNIlpMlsaY7rj/j5OdmR/3WY1i17g9nKSDGKyddZUr+ba8Al/dO0g7qiScj3p6a3QlSf149xgFUInK1YRkiQ1sLgu17BUwt2Bx1Ca2fipDHGHwDL01PeLpgO2UpsYNml5K5c="
